resume_from_checkpoint_path: None
result_path: '/kaggle/working'
pretrained_model_name_or_path: './donut-base'
dataset_name_or_paths: 
  - 'dataset/invoice_ocr'
sort_json_key: False
train_batch_sizes: 
  - 1
val_batch_sizes: 
  - 1
input_size: 
  - 1280
  - 960
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 1e-05
warmup_steps: 300
num_training_samples_per_epoch: 800
max_epochs: 100
max_steps: -1
num_workers: 4
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
exp_name: 'train_invoice'
exp_version: '20240229_005733'